name: anteros_flutter_app
description: A AnterosFlutter Demo App

version: 1.0.9+10

environment:
  sdk: ">=2.12.0 <3.0.0"
module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  anterosflutter: 
    path: /Users/relevantsolutions/anterosflutter
  webview_flutter: ^3.0.4
  cupertino_icons: ^1.0.3
  flutter_riverpod: ^1.0.3
  google_fonts: ^2.3.1
  hive: ^2.1.0
  path_provider: ^2.0.9
  url_launcher: ^6.0.20
  widget_with_codeview: ^2.0.1+2
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  get: 4.6.1
  http: ^0.13.4
  flutter_vector_icons: ^1.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/gif/success1.gif
    - lib/assets/gif/otp.gif
    - lib/assets/icons/allign.png
    - lib/assets/icons/Rotation.png
    - lib/assets/icons/scaling.png
    - lib/assets/icons/size.png
    - lib/assets/icons/slide.png
    - lib/assets/icons/gflogo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Roboto-Black.ttf
          weight: 900
    - family: GFFontIcons
      fonts:
        - asset: lib/assets/fonts/gfFontIcon.ttf
          weight: 400

    - family: GFFontIcons2
      fonts:
        - asset: lib/assets/fonts/gfFontIcons2.ttf
          weight: 400

    - family: GFSocialFonts
      fonts:
        - asset: lib/assets/fonts/gfSocialFonts.ttf
          weight: 400

    - family: GFIconFonts
      fonts:
        - asset: lib/assets/fonts/gfIconFonts.ttf
          weight: 400

    - family: GFIcons
      fonts:
        - asset: lib/assets/fonts/loader.ttf
          weight: 400

    - family: GFIconsnew
      fonts:
        - asset: lib/assets/fonts/newcomp.ttf
          weight: 400

    - family: GFIconsneww
      fonts:
        - asset: lib/assets/fonts/new.ttf
          weight: 400
