name: anterosflutter
description: Anteros Widgets package for Flutter.
version: 0.0.2
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0  
  cached_network_image: 3.2.0
  regexpattern: ^2.0.1
  characters: ^1.1.0
  collection: ^1.15.0
  crypto: ^3.0.0
  meta: ^1.3.0
  path: ^1.8.0
  time: ^2.0.0
  universal_platform: ^1.0.0+1
  material_color_utilities:
  flutter_colorpicker: ^1.0.3
  image: ^3.1.3
  flutter_keyboard_visibility: ^5.2.0
  phone_number: ^0.12.0+2
  file_picker: ^4.5.1
  community_material_icon: ^5.9.55
  permission_handler: ^9.2.0
  image_picker: ^0.8.5
  google_maps_flutter: ^2.1.4
  brasil_fields: ^1.4.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/opacity.png

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
